package com.application.walker.service;

import java.util.Date;

/**
 * Creditcard generated by hbm2java
 */
public class Creditcard implements java.io.Serializable {

	private Integer id;
	private User user;
	private String creditcardNumber;
	private Date creditcardExpirydate;
	private String creditcardVerificationcode;
	private int userId;

	public Creditcard() {
	}

	public Creditcard(User user, String creditcardNumber,
			Date creditcardExpirydate, String creditcardVerificationcode,
			int userId) {
		this.user = user;
		this.creditcardNumber = creditcardNumber;
		this.creditcardExpirydate = creditcardExpirydate;
		this.creditcardVerificationcode = creditcardVerificationcode;
		this.userId = userId;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	public String getCreditcardNumber() {
		return this.creditcardNumber;
	}

	public void setCreditcardNumber(String creditcardNumber) {
		this.creditcardNumber = creditcardNumber;
	}

	public Date getCreditcardExpirydate() {
		return this.creditcardExpirydate;
	}

	public void setCreditcardExpirydate(Date creditcardExpirydate) {
		this.creditcardExpirydate = creditcardExpirydate;
	}

	public String getCreditcardVerificationcode() {
		return this.creditcardVerificationcode;
	}

	public void setCreditcardVerificationcode(String creditcardVerificationcode) {
		this.creditcardVerificationcode = creditcardVerificationcode;
	}

	public int getUserId() {
		return this.userId;
	}

	public void setUserId(int userId) {
		this.userId = userId;
	}

}
