package com.application.walker.service;

import javax.persistence.Entity;

/**
 * User generated by hbm2java
 */
@Entity
public class User implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer id;
	private Address address;
	private String firstName;
	private String lastName;
	private String username;
	private String dob;
	private String emailAddress;
	private Creditcard creditcard;

	public User() {
	}

	public User(Address address, String username, String emailAddress) {
		this.address = address;
		this.username = username;
		this.emailAddress = emailAddress;
	}

	public User(Address address, String firstName, String lastName,
			String username, String dob, String emailAddress,
			Creditcard creditcard) {
		this.address = address;
		this.firstName = firstName;
		this.lastName = lastName;
		this.username = username;
		this.dob = dob;
		this.emailAddress = emailAddress;
		this.creditcard = creditcard;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Address getAddress() {
		return this.address;
	}

	public void setAddress(Address address) {
		this.address = address;
	}

	public String getFirstName() {
		return this.firstName;
	}

	public void setFirstName(String firstName) {
		this.firstName = firstName;
	}

	public String getLastName() {
		return this.lastName;
	}

	public void setLastName(String lastName) {
		this.lastName = lastName;
	}

	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	public String getDob() {
		return this.dob;
	}

	public void setDob(String dob) {
		this.dob = dob;
	}

	public String getEmailAddress() {
		return this.emailAddress;
	}

	public void setEmailAddress(String emailAddress) {
		this.emailAddress = emailAddress;
	}

	public Creditcard getCreditcard() {
		return this.creditcard;
	}

	public void setCreditcard(Creditcard creditcard) {
		this.creditcard = creditcard;
	}

}
