package com.application.walker.service;

import java.util.HashSet;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;

/**
 * User generated by hbm2java
 */
//User and Address has one to many mapping (many users at one address)
//User and coach has one to many mapping (many users have one coach)

@Entity
public class User implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	
	private Integer id;
	private Address address;
	private String firstName;
	private String lastName;
	private String username;
	private String dob;
	private String emailAddress;
	private Creditcard creditcard;
	
	//one coach many users
//	@ManyToOne
//	@JoinColumn(name = "coach_id")
	private Coach coach;
//	//means one user and many health records
	
	private Set<health> health = new HashSet<health>();
	
	@OneToMany(targetEntity=health.class,mappedBy="id",cascade=CascadeType.ALL,fetch=FetchType.LAZY)
	public Set<health> getHealth() {
		return health;
	}

	public void setHealth(Set<health> health) {
		this.health = health;
	}

	public User() {
	}

	public User(Address address, String username, String emailAddress) {
		this.address = address;
		this.username = username;
		this.emailAddress = emailAddress;
	}

	public User(Address address, String firstName, String lastName,
			String username, String dob, String emailAddress,
			Creditcard creditcard) {
		this.address = address;
		this.firstName = firstName;
		this.lastName = lastName;
		this.username = username;
		this.dob = dob;
		this.emailAddress = emailAddress;
		this.creditcard = creditcard;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Address getAddress() {
		return this.address;
	}

	public void setAddress(Address address) {
		this.address = address;
	}

	public String getFirstName() {
		return this.firstName;
	}

	public void setFirstName(String firstName) {
		this.firstName = firstName;
	}

	public String getLastName() {
		return this.lastName;
	}

	public void setLastName(String lastName) {
		this.lastName = lastName;
	}

	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	public String getDob() {
		return this.dob;
	}

	public void setDob(String dob) {
		this.dob = dob;
	}

	public String getEmailAddress() {
		return this.emailAddress;
	}

	public void setEmailAddress(String emailAddress) {
		this.emailAddress = emailAddress;
	}

	public Creditcard getCreditcard() {
		return this.creditcard;
	}

	public void setCreditcard(Creditcard creditcard) {
		this.creditcard = creditcard;
	}

	public Coach getCoach() {
		return coach;
	}

	public void setCoach(Coach coach) {
		this.coach = coach;
	}

}
